### ISSUE TITLE
windows support (node 0.6.5)?

### ISSUE THREAD

**Issue by outaTiME** [mikeal/watch#18]
Its possible to support windows ???

there are some kind of error in v.0.5.0 ...

```
Error: use fs.watch api instead
    at Object.watchFile (fs.js:734:11)
    at C:\Users\outaTiME\Development\projects\skycop\skyweb-mvc\node_modules\watch\main.js:56:10
    at C:\Users\outaTiME\Development\projects\skycop\skyweb-mvc\node_modules\watch\main.js:83:5
    at Object.oncomplete (C:\Users\outaTiME\Development\projects\skycop\skyweb-mvc\node_modules\watch\main.js:42:39)
```

and if we fix watchFile with watch ... another error comes (is change detected) ...

```
jake aborted.
TypeError: Object change has no method 'isDirectory'
    at FSWatcher.<anonymous> (C:\Users\outaTiME\Development\projects\skycop\skyweb-mvc\node_modules\watch\main.js:60:23)
    at FSWatcher.emit (events.js:70:17)
    at FSEvent.onchange (fs.js:652:12)
```

thks !

**Comment by togakangaroo** [comment]
Does this still not work? Is it possible to at least document this in the main README? I cannot `npm install` on windows 8.

**Comment by dandv** [comment]
I've installed watch just fine in node 0.12, and it works.
